name: Trigger Netlify Build
on:
  schedule:
    # Run at 08am every Mon, Wed, Friday
    - cron: '0 8 * * 1,3,5'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} $NETLIFY_BUILD_HOOK
        env:
            NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
